name: "Hola mundo"

on:
  push:
    branches: [main]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hola mundo desde GitHub Actions"
      - run: echo "hacemos pull del codigo"
      - run: echo "generar binario"
      - run: echo "publicar version"



